services:
  myDB:
    image: postgres:15.15
    container_name: my-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
